service: dynamodb-backup
frameworkVersion: "=1.26.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::orchestrated-test-dynamodb-backup"
    - Effect: "Allow"
      Action: 
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource: "arn:aws:s3:::orchestrated-test-dynamodb-backup/*"
    - Effect: "Allow"
      Action: "lambda:InvokeFunction"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:DescribeStream"
        - "dynamodb:GetRecords"
        - "dynamodb:GetShardIterator"
        - "dynamodb:ListStreams"
      Resource: "*"

package:
  include:
    - ./*.js
    - ./node_modules

functions:
  index:
    handler: index.backup

    events:
      - stream: arn:aws:dynamodb:ap-southeast-2:619797987959:table/BackupTest/stream/2018-02-01T05:14:27.659

    environment:
      BackupRegion: ap-southeast-2
      BackupBucket: orchestrated-test-dynamodb-backup
      BackupPrefix: test

resources:
  Resources:
    BackupBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: orchestrated-test-dynamodb-backup
        VersioningConfiguration:
          Status: "Enabled"
